### ISSUE TITLE
an error when running image_demo.py

### ISSUE THREAD

**Issue by kaishijeng** [voidrank/FastMask#1]
I follow the instruction to install all required SWs and download a pretrained model to try out demo with the following command, but encounter the following error. Do you know why?

 python image_demo.py 0 fm-res39zoom  /home/fc/Pictures/pedestrian4.jpg --init_weights=fm-res39_final.caffemodel
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1231 13:04:22.240295  2691 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W1231 13:04:22.240335  2691 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W1231 13:04:22.240339  2691 _caffe.cpp:125] Net('models/fm-res39zoom.test.prototxt', 1, weights='params/fm-res39_final.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 3657:24: Message type "caffe.LayerParameter" has no field named "sliding_window_param".
F1231 13:04:22.242545  2691 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/fm-res39zoom.test.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by voidrank** [comment]
Hi!

Maybe that's because you installed Caffe in the global environment and the program imported wrong Caffe.
Make sure your code can import correct Caffe.

You can simply change all 

> `sys.path.append(os.path.abspath("caffe-fm/python"))`

into

> `sys.path.insert(0, os.path.abspath("caffe-fm/python"))`
