### ISSUE TITLE
image_demo.py error

### ISSUE THREAD

**Issue by khahn0213** [voidrank/FastMask#18]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1211 02:23:10.587009 142111 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W1211 02:23:10.587072 142111 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W1211 02:23:10.587080 142111 _caffe.cpp:142] Net('models/fm-res39.test.prototxt', 1, weights='params/fm-res39_final_params.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 3629:24: Message type "caffe.LayerParameter" has no field named "sliding_window_param".
F1211 02:23:10.601371 142111 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/fm-res39.test.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

Hello, I met this error and I read previous closed issue which mentioned about this error, but it doesn't work for me. 
My CUDA version is 8.0, so I think CUDA version is not a problem... (I've read all of issue...)

**Comment by voidrank** [comment]
Hi, @khahn0213 
It's probably because you were using caffe of original version. Plz download all the submodules and thus compile fm-caffe.

**Comment by khahn0213** [comment]
Oh okay i try ur suggestion
Sincerely thanks for ur reply~!!
