### ISSUE TITLE
Instance Classification

### ISSUE THREAD

**Issue by pribadihcr** [voidrank/FastMask#3]
Hi,

Is it possible extend to instance aware classification?

Thanks

**Comment by voidrank** [comment]
Hi,

it is easy to extend by adding a category-aware loss in the head module. For more accurate instance aware segmentation, out new work FastMask-v2 is in process :)

**Comment by pribadihcr** [comment]
Hi @voidrank,

Thank for the responds,

I hope it is faster than  the "Instance-aware Semantic Segmentation via Multi-task Network Cascades".
Isn't it?.

**Comment by voidrank** [comment]
Of cause :)

**Comment by pribadihcr** [comment]
Hi,

For the category-aware. Can we put some layers after seg_2 layer. For example, put Fully Connected layer with output number of class, and calculate the loss with gt_cats ?

**Comment by voidrank** [comment]
Hi, @pribadihcr 
It seems to be a great idea. But unfortunately, we didn't try it.
We are very pleased to see your experiments if you will.

**Comment by pribadihcr** [comment]
Hi @voidrank,

Unfortunately, the idea didn't work. One question, if the training only see one class per iteration, does the method work ?, because in default setting, the FastMask's minibatch is 1 right?

**Comment by voidrank** [comment]
Hi @pribadihcr 
Well, there are quite many ways of optimization but maybe only few of them works. But I'm so sorry that we didn't do the experiment you described. 
From your description, I see that maybe you are not familiarized with the optimization of FastMask. I suggest that you should read our paper again or read [FRCN](https://github.com/rbgirshick/py-faster-rcnn). It would help.
