### ISSUE TITLE
Batch Layer

### ISSUE THREAD

**Issue by pribadihcr** [voidrank/FastMask#7]
Hi @voidrank,

How is exactly batch filter performed?. which code of caffe layer that point that operation?.
Thanks

layer { name: "batch_filter" type: "TopK" bottom: "sample" bottom: "mask_filter" bottom: "gt_masks" top: "filted_sample" }

**Comment by voidrank** [comment]
You can get top k masks from the first bottom blob ordered by the values of the second bottom blob. The value k is determined by the shape of the third bottom blob.

**Comment by pribadihcr** [comment]
Thanks. its clear. I have to read the prototxt and the caffe layer's src.
