### ISSUE TITLE
Not enought memory

### ISSUE THREAD

**Issue by dark0n7** [voidrank/FastMask#9]
I tried to run test 
python image_demo.py 0 fm-res39 test.jpg --init_weights=fm-res39_final.caffemodel
but got this:
I0212 22:26:45.281725  4787 net.cpp:270] This network produces output masks
I0212 22:26:45.281733  4787 net.cpp:270] This network produces output top_k
I0212 22:26:45.289829  4787 net.cpp:283] Network initialization done.
I0212 22:26:45.503679  4787 upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: params/fm-res39_final.caffemodel
I0212 22:26:45.503748  4787 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
I0212 22:26:45.503758  4787 net.cpp:761] Ignoring source layer gt_objn_data_1_split
I0212 22:26:45.503764  4787 net.cpp:761] Ignoring source layer gt_masks_data_2_split
I0212 22:26:45.543159  4787 net.cpp:761] Ignoring source layer obj_reshape
I0212 22:26:45.543190  4787 net.cpp:761] Ignoring source layer objn_filter
I0212 22:26:45.543195  4787 net.cpp:761] Ignoring source layer loss_obj
I0212 22:26:45.544867  4787 net.cpp:761] Ignoring source layer atts_atts_reshape_0_split
I0212 22:26:45.544893  4787 net.cpp:761] Ignoring source layer loss_att
I0212 22:26:45.553189  4787 net.cpp:761] Ignoring source layer reshape
I0212 22:26:45.553220  4787 net.cpp:761] Ignoring source layer gt_masks_reshape_reshape_0_split
I0212 22:26:45.553225  4787 net.cpp:761] Ignoring source layer loss_seg
F0212 22:26:46.166999  4787 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted (core dumped)

test image is small.
I have Geforce  1050 with 4 Gb memory. Is FreeMask really needs more memory to run or it some sort of software problems?
(There is no such problem with FB Deepmask on this system)

**Comment by voidrank** [comment]
Hi, @dark0n7 
Yes, it really needs so much memory even thought we spent some time in optimizing memory cost.
Memory saving is a common problem in the implementation of CNN architecture especially some novel operations such as attention we introduced in FastMask. 
However, you can simply reduce the size of the input image in configs/***.json. It would help.
Actually, we are busy in developing a smaller, quicker and more accuracy FastMask. I hope our subsequent version of FastMask will help you in the future.

**Comment by dark0n7** [comment]
Thank you for our answer! 
I'll try to reduce size.
